### PR TITLE
Added PHP UG Wellington

### PR DESCRIPTION
**Pull request by deberoppa**

### CODE REVIEW

**Comment by woecifaun** [comment]
Hello,

Thank you very much for your support. :smile: I'll merge/deploy it asap…

**Comment by woecifaun** [comment]
Hi @deberoppa,

PHP UG Wellington is now officialy on the list of PUGs supporting the project, I mean it's in production. :smile: Thank you very much.

Could it be possible to have the PHP UG Wellington in a larger size for the final video? around 800 pixels wide should do it. If so, you can send it to me at woecifaun [at] gmail

Cheers

**Comment by deberoppa** [comment]
@woecifaun Awesome :)

I actually sent an email with the logos of the Wellington and Auckland user groups to the team@ email address just ten minutes ago but it bounced back. Will send them to your private email address.

**Comment by woecifaun** [comment]
Ok ;-) just saw that.

**Pull request merged**
