### PR TITLE
Added Kaunas PHP usergroup.

### PR DESCRIPTION
**Pull request by Pawka**

### CODE REVIEW

**Comment by woecifaun** [comment]
Hello @Pawka,

Thank you for supporting the project 😀,

Is there any chance you have the logo in a bigger size for including in the video? like around 800 pixel wide. If not do you mind if I try to make the SVG of Kaunas PHP based on the logo you provided?

Thanks again.

**Comment by Pawka** [comment]
I'm pretty sure I had it. I'll try search and will upload later today.

On Tue, Oct 13, 2015 at 12:14 AM, Faun notifications@github.com wrote:

> Hello @Pawka https://github.com/Pawka,
> 
> Thank you for supporting the project 😀,
> 
> Is there any chance you have the logo in a bigger size for including in
> the video? like around 800 pixel wide. If not do you mind if I try to make
> the SVG of Kaunas PHP based on the logo you provided?
> 
> Thanks again.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/afup/haphpy-birthday/pull/146#issuecomment-147524621.

## 

  .^.   Povilas Balzaravičius \* Software Engineer at Uber Technologies
  /V\   phone: +37060117345 \* Skype: pawka.lt
 /(_)\  pawka.linija.net \* github.com/Pawka
  ^ ^

**Comment by woecifaun** [comment]
Hello @Pawka 

I just started to edit the final movie. I wonder if you could have found a larger logo to include in the video. :-)

Thank you in advance.

**Comment by Pawka** [comment]
@woecifaun I've replaced my picture with other, better quality photo already few weeks ago. Photo is different, because I  was not able find high quality of previous one.

P.S. Can't wait for video! :-)

**Comment by woecifaun** [comment]
@Pawka 

Sorry I'm lost. Are you talking about the Kaunas PHP logo in the  [supporting list](http://haphpy-birthday.net/en/contributions#php-user-groups) dedicated to PHP user groups or about a contribution via the form?

I'm looking for a larger version of the following logo:
kaunasphp

Thanks.

**Pull request merged**
