### PR TITLE
add PUG Roma

### PR DESCRIPTION
**Pull request by garak**

### CODE REVIEW

**Comment by woecifaun** [comment]
Hi @garak 

Thank you for supporting the project :smile: You're just in time as the movie is almost edited.

Could you send a taller version of the logo to include in the video ? around 600 pixels high or wide should do it. You can send it to woecifaun [at] gmail

Thanks again

**Comment by garak** [comment]
An SVG file would be fine?

**Comment by woecifaun** [comment]
@garak, it would be perfect :+1:

**Comment by woecifaun** [comment]
[GitHub rate limit reached](https://travis-ci.org/afup/haphpy-birthday/builds/92279237#L512)

I merge it.

**Pull request merged**
