### PR TITLE
display image contributions

### PR DESCRIPTION
**Pull request by agallou**
see #46

### CODE REVIEW

**Comment by woecifaun** [comment]
Hi thank you.

I'll look at your work as I was working on this one too.

I assigned myself to the https://github.com/afup/haphpy-birthday/issues/46 so you could see I was working on it. It didn't work apparently. :wink: I propose we assign ourselves on issue we are working on. What do you think ?

**Comment by woecifaun** [comment]
@agallou I will now add an instruction asking people to say they are working on an issue.

I hope this will prevent people working concurrently on the same issue.

**Comment by agallou** [comment]
sorry, when I started working on this, you haven't assigned yourself the issue. I should have made a comment on it. I'll do that for the next issues.

**Comment by woecifaun** [comment]
Hello @agallou, I delete the branch as the work I've done on my side is merged onto master. Sorry for the waste of time.

**Pull request closed without merging**
