### PR TITLE
Add "PHP Srbija" to PUGs list

### PR DESCRIPTION
**Pull request by nikolaposa**

### CODE REVIEW

**Comment by woecifaun** [comment]
Hi @nikolaposa 

Thanks for supporting HaPHPy Birthday. :-)

**Comment by woecifaun** [comment]
Oops, I forgot to ask if by any chance you have the logo in a larger size to include in the final movie. Around 800 pixels wide should do it. If so you can send it to me at woecifaun [at] gmail.

Cheers.

**Comment by nikolaposa** [comment]
@woecifaun No problem, I'll email you with some larger logo soon.

**Comment by woecifaun** [comment]
Received it. Thanks :-)

And thanks again for your support.

**Comment by nikolaposa** [comment]
No problem, you're welcome. :+1:

**Pull request merged**
