### PR TITLE
Add MalangPHP to the list

### PR DESCRIPTION
**Pull request by praswicaksono**
sorry for late response,

here we go, ready for review ;)

### CODE REVIEW

**Comment by woecifaun** [comment]
@Atriedes Thanks for the support of MalangPHP

I'll merge that as soon as I can. :-)

**Comment by praswicaksono** [comment]
the logo is quite unusual, please let me know if it don't fit with website.

**Comment by woecifaun** [comment]
You have a great logo.

I think we can use only the lion head with the circle around for the website. Your name and location is displayed on the side of the logo anyway.
In the video, I'll use the full logo you provided.

Just let me know.

**Comment by praswicaksono** [comment]
You can crop by yourself or I need to edit the image? I have it on PNG format, I just only convert it in SVG

**Comment by woecifaun** [comment]
I'll do it. SVG is appropriate for that. :smile:

**Comment by praswicaksono** [comment]
Cool, thanks!

**Pull request merged**
