### PR TITLE
SDPHP URL uses HTTP

### PR DESCRIPTION
**Pull request by ericvanjohnson**

### CODE REVIEW

**Comment by woecifaun** [comment]
Travis CI Build error: `You have reached GitHub hour limit! Actual limit is: 60` -> merge ok

**Comment by woecifaun** [comment]
Hi @ericvanjohnson ,

It's fixed in production. :-)

**Comment by ericvanjohnson** [comment]
Thanks

**Comment by woecifaun** [comment]
@ericvanjohnson 

Oops, I forgot to ask if by any chance you have the logo in a larger size to include in the final movie. Around 800 pixels wide should do it. If so you can send it to me at woecifaun [at] gmail.

Cheers.

**Comment by ericvanjohnson** [comment]
Yeah I tried sending it team at haphpy-birthday dot net which were the directions on the site but it bounced. Will forward it to you now. ..... and sent :-)

**Pull request merged**
