### PR TITLE
Add PHP Puebla to PUGs list.

### PR DESCRIPTION
**Pull request by MontealegreLuis**

### CODE REVIEW

**Comment by woecifaun** [comment]
Hello @MontealegreLuis,

Thank you for your support. The SVG is aliased on Firefox and doesn't display on desktop Safari.

If you don't mind, I will clean it to optimize its display in browsers. I can do it quite quickly.

**Comment by MontealegreLuis** [comment]
Oh I didn't know, it's okay. Please change it. Thank you.

**Comment by woecifaun** [comment]
Hello @MontealegreLuis 

I had to use the logo on PHP Puebla website to generate a png with the proper dimensions for the PUGs list.

The SVG you provided in this PR is just  a container for a squashed JPG image (the circle around the elephant appeared oval).

**Just le me know on https://github.com/afup/haphpy-birthday/pull/119/files, if you're ok with the logo and I'll merge it**

Thanks

**Comment by MontealegreLuis** [comment]
It looks really good. Thank you for fixing it. :smile:

**Pull request merged**
