### PR TITLE
Added PHP UG Munich

### PR DESCRIPTION
**Pull request by Zifius**

### CODE REVIEW

**Comment by woecifaun** [comment]
Thanks for supporting the project :smile: 

I'll merge it as soon as possible…

**Comment by woecifaun** [comment]
Hi @Zifius 

PHP UG Munich is now officialy on the list of PUGs supporting the project, I mean it's in production. :smiley: Thank you very much.

Could it be possible to have the PHP UG Munich in a larger size for the final video? at least 600 pixels wide should do it. If so, you can send it to me at woecifaun [at] gmail

Cheers

**Comment by Zifius** [comment]
Hi @woecifaun,

my pleasure. I've asked the UG leaders about the hi-res logo, will forward it to you when they respond

Best,
Alex

**Comment by woecifaun** [comment]
Great, thanks. I'm looking forward to it.

**Pull request merged**
